name: Check pull request

on:
  pull_request

jobs:
  Validate-PR:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          
      # Executing install and test
      - name: Preparing dashboard
        run: chmod +x ./dashboard.sh

      - name: Install packages
        run: ./dashboard.sh install

      - name: Run precommits (for code formatting)
        run: ./dashboard.sh precommit

      - name: Commit changes back
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github_actions
          message: "Formatting code with precommits"
          add: "."
          push: true

      - name: Run tests
        run: ./dashboard.sh test